[package]
name = "mmaptest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
io-uring = "0.6.0"
madvise = "0.1.0"
memmap = "0.7.0"
tokio = { version = "1.31.0", features = ["full"] }
